name: Mt-KaHyPar CI

on: [ push, pull_request ]

jobs:
  mt_kahypar_test_suite:
    runs-on: ubuntu-20.04
    env:
      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
      CI_ACTIVE : 1

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
         fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get install libtbb-dev libhwloc-dev libboost-program-options-dev lcov gcovr

      - name: Install Mt-KaHyPar Test Suite
        run: |
          git submodule init
          git submodule update
          rm -rf debug
          mkdir debug
          cd debug
          cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DKAHYPAR_USE_GCOV=ON -DKAHYPAR_CI_BUILD=ON
          make -j2 mt_kahypar_tests;

      - name: Run Mt-KaHyPar Tests
        run: |
          cd debug
          ./tests/mt_kahypar_tests;

      - name: Report Code Coverage
        run: |
          cd debug
          lcov --directory . --capture --output-file coverage.info;
          lcov --remove coverage.info '/usr/*' --output-file coverage.info;
          lcov --list coverage.info;
          gcovr -r ../ -x > report.xml;
          cd ..
          bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

  mt_kahypar_integration_tests:
    runs-on: ubuntu-20.04
    env:
      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
      CI_ACTIVE : 1

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
         fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get install libtbb-dev libhwloc-dev libboost-program-options-dev lcov gcovr

      - name: Install Mt-KaHyPar Integration Tests
        run: |
          git submodule init
          git submodule update
          rm -rf build
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_CI_BUILD=ON
          make -j2 MtKaHyPar
          make -j2 VerifyPartition

      - name: Run Mt-KaHyPar Integration Tests
        run: |
          ./tests/end_to_end/integration_tests.py

  mt_kahypar_interface_tests:
    runs-on: ubuntu-20.04
    env:
      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
      CI_ACTIVE : 1

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
         fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get install libtbb-dev libhwloc-dev libboost-program-options-dev lcov gcovr

      - name: Run Mt-KaHyPar C Library Interface Tests
        run: |
          git submodule init
          git submodule update
          rm -rf build
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_CI_BUILD=ON
          make -j2 interface_test

      - name: Build Mt-KaHyPar Python Interface
        run: |
          cd build
          make mtkahypar_python -j2

      - name: Run Mt-KaHyPar Python Interface Tests
        run: |
          cd python/tests
          cp ../../build/python/mtkahyparhgp*.so mtkahyparhgp.so
          cp ../../build/python/mtkahypargp*.so mtkahypargp.so
          python3 test_mtkahyparhgp.py -v
          python3 test_mtkahypargp.py -v

  mt_kahypar_windows_build:
    runs-on: windows-latest
    env:
      CI_ACTIVE : 1

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
         fetch-depth: 1

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: git make

      - name: Install Boost and TBB
        shell: msys2 {0}
        run: |
          pacman --noconfirm -S mingw-w64-x86_64-boost mingw-w64-x86_64-tbb mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc

      - name: Put MSYS2_MinGW64 on Path
        run: |
          echo "${{ runner.temp }}/msys64/mingw64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Rename TBB library file
        run: |
          Ren ${{ runner.temp }}/msys64/mingw64/lib/libtbb12.dll.a ${{ runner.temp }}/msys64/mingw64/lib/libtbb.dll.a

      - name: Install Mt-KaHyPar Multilevel Tests
        shell: msys2 {0}
        run: |
          git submodule init
          git submodule update
          rm -rf build
          mkdir build
          cd build
          export CMAKE_GENERATOR="MSYS Makefiles"
          /mingw64/bin/cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_DOWNLOAD_BOOST=On -DKAHYPAR_CI_BUILD=ON
          make -j2 mt_kahypar_tests

      - name: Run Mt-KaHyPar Tests
        shell: msys2 {0}
        run: |
          cd build
          ./tests/mt_kahypar_tests
