name: Performance Benchmark

on: [ push, pull_request ]

jobs:
  performance_benchmark:
    runs-on: ubuntu-latest
    env:
      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
      PERFORMANCE_THRESHOLD: "1.1"

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
         fetch-depth: 2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libtbb-dev libhwloc-dev libboost-program-options-dev

      - name: Install Current Version of Mt-KaHyPar
        run: |
          git submodule init
          git submodule update
          rm -rf build
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=RELEASE
          make KaHyPar -j2

      - name: Run Benchmark on Current Version of Mt-KaHyPar
        run: |
          current_sha=$(git rev-parse --short "$GITHUB_SHA")
          echo "$current_sha" >> current_sha.txt
          cd .github/workflows
          mkdir results
          cd results
          mkdir $current_sha
          cd ..
          bash -x benchmark.sh ../../build/mt-kahypar/application/KaHyPar ../../config/quality_preset.ini results/$current_sha
          cd ../..

      - name: Install Previous Version of Mt-KaHyPar
        run: |
          git checkout HEAD^
          git submodule init
          git submodule update
          rm -rf build
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=RELEASE
          make KaHyPar -j2

      - name: Run Benchmark on Previous Version of Mt-KaHyPar
        run: |
          current_sha=`cat current_sha.txt`
          previous_sha=$(git rev-parse --short HEAD)
          echo "$previous_sha" >> previous_sha.txt
          cd .github/workflows
          cd results
          mkdir $previous_sha
          cd ..
          bash -x benchmark.sh ../../build/mt-kahypar/application/KaHyPar ../../config/quality_preset.ini results/$previous_sha
          cd ../..

      - name: Create CSV Files
        run: |
          cd .github/workflows
          ./grep_experiment_results.sh results
          cd ../..

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Create Benchmark Results
        run: |
          cd .github/workflows
          current_sha=`cat current_sha.txt`
          previous_sha=`cat previous_sha.txt`
          Rscript --vanilla results.R $PWD results $previous_sha $current_sha
          cd ../..

      - name: Verify Performance Regression
        run: |
          cd .github/workflows
          running_time_ratio=`cat running_time_ratio.txt`
          if (( $(echo "$running_time_ratio > $PERFORMANCE_THRESHOLD" | bc -l) )); then
            echo "Running time degrades by a factor of $running_time_ratio (must be smaller than $PERFORMANCE_THRESHOLD)"
            exit 1
          fi
          echo "Running time ratio is $running_time_ratio"

          quality_ratio=`cat quality_ratio.txt`
          if (( $(echo "$quality_ratio > $PERFORMANCE_THRESHOLD" | bc -l) )); then
            echo "Running time degrades by a factor of $running_time_ratio (must be smaller than $PERFORMANCE_THRESHOLD)"
            exit 1
          fi
          echo "Quality ratio is $quality_ratio"
          cd ../..

      - name: Upload CSV Files
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: .github/workflows/results/*.csv

